# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "controler" do |controler|
    controler.vm.box = "geerlingguy/ubuntu2004"
    controler.vm.hostname = "controler"
    controler.vm.network "private_network", type: "static", ip: "192.168.10.1", virtualbox__intnet: true
    controler.vm.provider "virtualbox" do |vb|
      vb.name = "controler"
      vb.memory = "2048"
      vb.cpus = 2
    end
    controler.vm.provision "shell" do |s|
      s.path = "install_ansible.sh"
    end
  end

  config.vm.define "node" do |node|
    node.vm.box = "geerlingguy/ubuntu2004"
    node.vm.hostname = "node"
    node.vm.network "private_network", type: "static", ip: "192.168.10.2", virtualbox__intnet: true
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node"
      vb.memory = "2048"
      vb.cpus = 2
    end
    node.vm.provision "shell" do |shell|
      shell.path = "install_ansible.sh"
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
