# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.hostname = "master"
  config.vm.network "private_network", type: "static", ip: "192.168.99.10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "master"
    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.provision :shell do |shell|
    shell.path = "install_kubernetes.sh"
    shell.args = ["master", "192.168.99.10"]
  end
  workers = 2
  (1..workers).each do |i|
    config.vm.define "worker#{i}" do |node|
      node.vm.box = "geerlingguy/centos7"
      node.vm.hostname = "worker#{i}"
      node.vm.network "private_network", type: "static", ip: "192.168.99.#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "worker#{i}"
        vb.memory = "2048"
        vb.cpus = 2
      end
      node.vm.provision :shell do |shell|
        shell.path = "install_kubernetes.sh"
        shell.args = ["worker", "192.168.99.10"]
      end
    end
  end
end
